# Generated by Django 4.2.5 on 2023-12-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Kamentariya', 'verbose_name_plural': 'Kamentariyalar'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=800),
        ),
    ]
